### PR TITLE
Externalize a few classes. Add utility method for Timestamps.

### PR DESCRIPTION
**Pull request by mikhailmikhaylov**

### CODE REVIEW

**Comment by mikhailmikhaylov** [comment]
I've added tests for all non-test code, but coverage decreased, I can't find out why.

**Comment by mikhailmikhaylov** [comment]
I've externalized classes to reuse them for tests at gae-java project

**Comment by AlexanderLitus** [comment]
Yeah, I experienced such a bug with the coverage too.

**Comment by AlexanderLitus** [comment]
And now the coverage is increased. LGTM.

**Pull request merged**
