### PR TITLE
Deeply nested `Query` filters

### PR DESCRIPTION
**Pull request by armiol**
This changeset brings the [upcoming changes in Query DSL](https://github.com/SpineEventEngine/base/pull/644) to `client` and `server` modules.

**`Query` Tree**

`core-java` defines Protobuf-based `Query` language. It serves to transfer Query instances over the wire. Previously, it only supported two levels of filters. In scope of this PR any level of nesting in the Query filters becomes supported, both in the Proto definitions, and by the in-memory implementations of `Storage`s. Effectively, a Protobuf `Query` object now holds a tree of filters.

The extension to the Proto definitions is additive. Thus, the previous version of Proto definitions will still work with the proposed implementation.

Here is an example of a query which has more than two levels of nesting:

```java
Car.query()
    .either(car -> car.color().is(Color.RED)
                      .manufacturer().is(Manufacturers.ferrari()),

		car -> car.either(its -> its.color().is(Color.BLACK),
			          or -> or.color().is(Color.WHITE))
		          .acceleration().isGreaterThan(1.4)    // G
		          .topSpeed().isGreaterThan(160)        //MPH
	)
    .price().isLessThan(iAmWillingToSpend)
    .build();
```

**API changes**

* In order to allow convenient querying from outside of its package, `InboxColumn` definitions are made `public`. This is a change required by the dependant libraries, such as Spine's Datastore connector.

* `TenantIndex.createDefault()` has been renamed to `TenantIndex.defaultMultitenant()`, for clarity.

### CODE REVIEW

**Comment by armiol** [comment]
@dmdashenkov @alexander-yevsyukov PTAL. The tests will come through after https://github.com/SpineEventEngine/base/pull/644 is merged.

**Review by dmdashenkov — CHANGES_REQUESTED** [review]
Please add an example showing how to use deeply nested query parameters. Here or in the `base` PR. Other than that, LGTM.

**Review by alexander-yevsyukov — COMMENTED** [review]
Assuming Dima's comments, LGTM.

**Comment by armiol** [comment]
@dmdashenkov I have added an example to the PR description here.
PTAL.

**Review by dmdashenkov — APPROVED** [review]
LGTM.

**Pull request merged**
