### PR TITLE
Fix "java_outer_classname" option in person.proto (avoid conflict wit…

### PR DESCRIPTION
**Pull request by AlexanderLitus**
…h PersonName message).

### CODE REVIEW

**Comment by mikhailmikhaylov** [comment]
LGTM

**Comment by AlexanderLitus** [comment]
PTAL

**Comment by AlexanderLitus** [comment]
There are only double and float in proto3.

**Comment by AlexanderLitus** [comment]
PTAL.

**Comment by alexander-yevsyukov** [comment]
Amount as Any is not a good idea. We obviously need to be definite here.

**Comment by alexander-yevsyukov** [comment]
Please apply the fix to the outer class name and have money matter as a separate branch.

**Comment by alexander-yevsyukov** [comment]
That is, remove adding money definition from this pull request, and then merge it. Money is a separate matter. Please don't mix things. It delays progressing the code.

**Pull request merged**
