### PR TITLE
Business failures

### PR DESCRIPTION
**Pull request by alexander-yevsyukov**
Basic types and example defined. Further work needed to store failure and send it to clients.

### CODE REVIEW

**Comment by alexander-yevsyukov** [comment]
@mikhailmikhaylov, it turns out we don't need hacking Protobuf compiler for generating code that allows having Throwables that contain messages. It can be done easier via putting all the failures into the same file and writing throwables manually.

This is what we should automate. See example in the `throwable` package.

**Comment by alexander-yevsyukov** [comment]
@AlexanderLitus 
@eugeniakotlyar, see the code of `TaskAggregate` in `failure` example for the new feature of Aggregates. We now can declare that a command handler method can throw business failures.
This way the API of each command handler is clear:
* It either produces an event (or a list of events). Or,
* It can throw one or more business failures (which are clearly visible in the method signature).

**Comment by mikhailmikhaylov** [comment]
LGTM

**Comment by eugeniakotlyar** [comment]
Thanks, added to the documentation.

On Thu, Jan 14, 2016 at 8:45 AM, Alexander Yevsyukov <
notifications@github.com> wrote:

> @AlexanderLitus <https://github.com/AlexanderLitus>
> @eugeniakotlyar <https://github.com/eugeniakotlyar>, see the code of
> TaskAggregate in failure example for the new feature of Aggregates. We
> now can declare that a command handler method can throw business failures.
> This way the API of each command handler is clear:
>
>    - It either produces an event (or a list of events). Or,
>    - It can throw one or more business failures (which are clearly
>    visible in the method signature).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineEventEngine/core-java/pull/76#issuecomment-171554726>
> .
>



-- 
Eugenia Kotlyar

System Analyst | TeamDev, Ltd.
Phone: +380 57 766-4300
eugenia.kotlyar@teamdev.com | www.teamdev.com

**Pull request merged**
