### PR TITLE
`EventEnricher` improvements

### PR DESCRIPTION
**Pull request by alexander-yevsyukov**

### CODE REVIEW

**Comment by alexander-yevsyukov** [comment]
@armiol please assign somebody to refactor the construction of `EventEnricher`. It would be better to have all the process inside the `Builder`. Now it's something here, something there.

**Comment by alexander-yevsyukov** [comment]
@armiol please also see #277. It would be good to address this issue while we're changing the `EventEnricher`.

**Comment by alexander-yevsyukov** [comment]
@alexander-aleksandrov have a look at the method object refactoring.

**Comment by alexander-yevsyukov** [comment]
@armiol thanks for reviewing the PR, and approving it. But I wanted also that you assign some of the guys to refactor and improve `EventEnricher` event further. See my comments above.

**Comment by alexander-yevsyukov** [comment]
@armiol I can probably do it myself, but I'd rather finish with applying `AggregatePart`s and test builders in Projects.

**Comment by armiol** [comment]
@alexander-yevsyukov so you wanted the changes to be appended here? If so, now I get it. 

I was actually planning to do some changes to the `EventEnricher` myself — to break the dependency circle. I will pick this PR up.

**Comment by alexander-yevsyukov** [comment]
@armiol yes, please pick it up.

**Pull request merged**
