### PR TITLE
Repackage testutil modules to io.spine.testing.*

### PR DESCRIPTION
**Pull request by vlad-lubenskyi**
This PR repackages `testutil-server`, `testutil-client`, and `testutil-core` module to be under `io.spine.testing.server`, `io.spine.testing.cient`, and `io.spine.testing.core` packages respectively.

Version is advanced to `0.10.48-SNAPSHOT`.

To perform the repackaging, I extended visibility of the following classes and methods:
* `AggregateCommandEndpoint`, `AggregateEventEndpoint`, `AggregateRejectionEndpoint` were package-private, became: (at)Internal public so they can be extended in `testutil-server`.
* `PmCommandEndpoint`, `PmEventEndpoint`, `PmRejectionEndpoint` were package-private, became: (at)Internal public so they can be extended in `testutil-server`.
* `ProjectionEndpoint` was package-private, became: (at)Internal public so it can be in `testutil-server`.
* `AggregateTransaction` was package-private, became: (at)Internal public;
* `PmTransaction` was package-private, became: (at)Internal public;
* `ProjectionTransaction` was package-private, became: (at)Internal public;
* `Repository.Lifecycle` was: private, became: protected.
* `CurrentTenant` was: package-private, became: (at)Internal public;
   * `get()`, `set()`, `clear()` were: package-private, became: public;

### CODE REVIEW

**Comment by vlad-lubenskyi** [comment]
@armiol PTAL

**Comment by armiol** [comment]
@vlad-lubenskyi please see [the approach](https://github.com/SpineEventEngine/core-java/pull/752/commits/cfcdf7aa01a2cbf8a80916575cc1902f661f9dc3) and continue. We need to hide most of the methods back.

**Comment by vlad-lubenskyi** [comment]
@armiol PTAL

**Comment by vlad-lubenskyi** [comment]
@armiol PTAL.

Codecov fails because of `AggregateMessageDispatcher.TestAggregateRepository` and similar classes. 

Their constructor and the single method exists only to expose those of the parent, so they can be mocked.

**Comment by armiol** [comment]
@vlad-lubenskyi please see #706 and make sure it's closed after this one is merged.

**Pull request merged**
