### PR TITLE
Add `@Route` annotation

### PR DESCRIPTION
**Pull request by alexander-yevsyukov**
This PR introduces `@Route` annotation for static methods of an entity class that would be a preferred way for arranging routing.  Currently we have to create a repository class _just_ for arranging routing. It it's too much code.

This PR only renames the `Route` functional interface to `RouteFn`, freeing up the name for the new annotation interface.
It does that very minimum to introduce this breaking change sooner.

Following PRs would:

  * Verify the correctness of applying the `@Route` annotation (presumably via using Java Annotation Processor).

  * Extend `BoundedContextBuilder` for creating a routing function over a default repository for a class, which has static methods annotated with `@Route`.

### CODE REVIEW

**Comment by alexander-yevsyukov** [comment]
@armiol, @dmdashenkov, please have a look at how I suggest to improve routing.

I have not implemented the functional part of it. I'd like to finalize the concept first.

**Comment by alexander-yevsyukov** [comment]
We also probably need to discuss #1466 and #905 in the context of this PR.

**Comment by armiol** [comment]
@alexander-yevsyukov I like the idea and the implementation.

It would be nice to have a Java-based test migrated to this approach as well.
Another thing, it would be nice to have a more detailed description of the feature in the PR description.

**Comment by alexander-yevsyukov** [comment]
> It would be nice to have a Java-based test migrated to this approach as well.
@armiol, I'm glad and will proceed with the implementation. But I'm not sure which ”test” did you mean? Or did you mean tests that currently employ repos just for routing?

**Comment by alexander-yevsyukov** [comment]
> Some of them redefined their routing as well. We could migrate one of them — whichever seemed convenient — to this approach.

@armiol, got it. Will do.

**Review by armiol — APPROVED** [review]
Apparently, I have already reviewed most of the files in this very PR. 

LGTM.

**Pull request merged**
